// #Sireum
package org.sireum.hamr.ir.util

import org.sireum._
import org.sireum.hamr.ir._
import org.sireum.message.{FlatPos, Position}

object Util {

  /// Relativize position URIs in an AIR model so that serialized JSON
  /// is portable across machines.
  ///
  /// AIR models produced by OSATE contain position URIs relative to the
  /// AADL workspace, which is fine since errors are reported back to OSATE
  /// which resolves relative URIs against the workspace.  AIR models
  /// generated by HAMR SysML, however, use absolute file URIs because
  /// the target IDE is not known at generation time.  Absolute URIs prevent
  /// AIR JSON files from being used as expected test results since the paths
  /// differ across developer machines.
  ///
  /// This method strips the longest matching source-path prefix from every
  /// Position URI in the model, producing paths of the form `/<relative-path>`.
  /// Source paths should include every directory whose files contributed to the
  /// model (e.g. the project root, additional --sourcepath entries, and the
  /// SysML AADL library directory).
  def relativizePosUris(a: Aadl, sourcePaths: ISZ[Os.Path]): Aadl = {
    var prefixes = ISZ[String]()
    for (sp <- sourcePaths) {
      var prefix = sp.toUri
      if (ops.StringOps(prefix).endsWith("/")) {
        prefix = ops.StringOps(prefix).substring(0, prefix.size - 1)
      }
      prefixes = prefixes :+ prefix
    }
    val scrubber = AirPositionRelativizer(prefixes)
    val result = scrubber.transformAadl(a)
    return result.getOrElse(a)
  }

  /// MTransformer that walks an AIR model and relativizes Position URIs.
  /// Each FlatPos whose uriOpt starts with one of the given prefixes has the
  /// longest matching prefix stripped, leaving a path like `/<relative-path>`.
  /// Positions that do not match any prefix are left unchanged.
  ///
  /// This transformer must override the `pre` hook for every AST node type
  /// that directly holds a Position field.  If a new node type with a Position
  /// field is added to the AIR AST and is not handled here, the JSON oracle
  /// check in the HAMR SysMLv2 test suites will catch it.
  @record class AirPositionRelativizer(val prefixes: ISZ[String]) extends MTransformer {

    /// Replace the URI in a FlatPos with a relative path by stripping the
    /// longest matching source-path prefix.  Returns the position unchanged
    /// if no prefix matches or if the position is not a FlatPos.
    def scrubPos(pos: Option[Position]): Option[Position] = {
      pos match {
        case Some(f: FlatPos) =>
          f.uriOpt match {
            case Some(uri) =>
              val uriOps = ops.StringOps(uri)
              var bestPrefix: String = ""
              for (p <- prefixes) {
                if (uriOps.startsWith(p) && p.size > bestPrefix.size) {
                  bestPrefix = p
                }
              }
              if (bestPrefix.size > 0) {
                return Some(f(uriOpt = Some(uriOps.substring(bestPrefix.size, uri.size))))
              } else {
                return pos
              }
            case _ => return pos
          }
        case _ => return pos
      }
    }

    override def preName(o: Name): MTransformer.PreResult[Name] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def pre_langastAttr(o: org.sireum.lang.ast.Attr): MTransformer.PreResult[org.sireum.lang.ast.Attr] = {
      return MTransformer.PreResult(T, MSome(o(posOpt = scrubPos(o.posOpt))))
    }

    override def pre_langastTypedAttr(o: org.sireum.lang.ast.TypedAttr): MTransformer.PreResult[org.sireum.lang.ast.TypedAttr] = {
      return MTransformer.PreResult(T, MSome(o(posOpt = scrubPos(o.posOpt))))
    }

    override def pre_langastResolvedAttr(o: org.sireum.lang.ast.ResolvedAttr): MTransformer.PreResult[org.sireum.lang.ast.ResolvedAttr] = {
      return MTransformer.PreResult(T, MSome(o(posOpt = scrubPos(o.posOpt))))
    }

    override def pre_langastExpBinary(o: org.sireum.lang.ast.Exp.Binary): MTransformer.PreResult[org.sireum.lang.ast.Exp] = {
      return MTransformer.PreResult(T, MSome(o(opPosOpt = scrubPos(o.opPosOpt))))
    }

    override def pre_langastExpUnary(o: org.sireum.lang.ast.Exp.Unary): MTransformer.PreResult[org.sireum.lang.ast.Exp] = {
      return MTransformer.PreResult(T, MSome(o(opPosOpt = scrubPos(o.opPosOpt))))
    }

    override def pre_langastTopUnitTruthTableUnit(o: org.sireum.lang.ast.TopUnit.TruthTableUnit): MTransformer.PreResult[org.sireum.lang.ast.TopUnit] = {
      return MTransformer.PreResult(T, MSome(o(
        stars = for (s <- o.stars) yield scrubPos(Some(s)).get,
        separator = scrubPos(Some(o.separator)).get)))
    }

    override def pre_langastTruthTableRow(o: org.sireum.lang.ast.TruthTable.Row): MTransformer.PreResult[org.sireum.lang.ast.TruthTable.Row] = {
      return MTransformer.PreResult(T, MSome(o(separator = scrubPos(Some(o.separator)).get)))
    }

    override def pre_langastResolvedInfoBuiltIn(o: org.sireum.lang.ast.ResolvedInfo.BuiltIn): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoPackage(o: org.sireum.lang.ast.ResolvedInfo.Package): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoEnum(o: org.sireum.lang.ast.ResolvedInfo.Enum): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoEnumElement(o: org.sireum.lang.ast.ResolvedInfo.EnumElement): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoObject(o: org.sireum.lang.ast.ResolvedInfo.Object): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoVar(o: org.sireum.lang.ast.ResolvedInfo.Var): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoMethod(o: org.sireum.lang.ast.ResolvedInfo.Method): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoMethods(o: org.sireum.lang.ast.ResolvedInfo.Methods): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoTuple(o: org.sireum.lang.ast.ResolvedInfo.Tuple): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoLocalVar(o: org.sireum.lang.ast.ResolvedInfo.LocalVar): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoFact(o: org.sireum.lang.ast.ResolvedInfo.Fact): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoTheorem(o: org.sireum.lang.ast.ResolvedInfo.Theorem): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def pre_langastResolvedInfoInv(o: org.sireum.lang.ast.ResolvedInfo.Inv): MTransformer.PreResult[org.sireum.lang.ast.ResolvedInfo] = {
      return MTransformer.PreResult(T, MSome(o(defPosOpt = scrubPos(o.defPosOpt))))
    }

    override def preGclSubclause(o: GclSubclause): MTransformer.PreResult[GclSubclause] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclGuarantee(o: GclGuarantee): MTransformer.PreResult[GclGuarantee] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclInvariant(o: GclInvariant): MTransformer.PreResult[GclInvariant] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclAssume(o: GclAssume): MTransformer.PreResult[GclAssume] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclIntegration(o: GclIntegration): MTransformer.PreResult[GclIntegration] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclCaseStatement(o: GclCaseStatement): MTransformer.PreResult[GclCaseStatement] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclInitialize(o: GclInitialize): MTransformer.PreResult[GclInitialize] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclCompute(o: GclCompute): MTransformer.PreResult[GclCompute] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclHandle(o: GclHandle): MTransformer.PreResult[GclHandle] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclLib(o: GclLib): MTransformer.PreResult[GclLib] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preInfoFlowClause(o: InfoFlowClause): MTransformer.PreResult[InfoFlowClause] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preGclStateVar(o: GclStateVar): MTransformer.PreResult[GclStateVar] = {
      return MTransformer.PreResult(T, MSome(o(attr = o.attr(scrubPos(o.posOpt)))))
    }

    override def preBTSUnaryExp(o: BTSUnaryExp): MTransformer.PreResult[BTSUnaryExp] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def preBTSBinaryExp(o: BTSBinaryExp): MTransformer.PreResult[BTSBinaryExp] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def preBTSLiteralExp(o: BTSLiteralExp): MTransformer.PreResult[BTSLiteralExp] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def preBTSNameExp(o: BTSNameExp): MTransformer.PreResult[BTSNameExp] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def preBTSIndexingExp(o: BTSIndexingExp): MTransformer.PreResult[BTSIndexingExp] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def preBTSAccessExp(o: BTSAccessExp): MTransformer.PreResult[BTSAccessExp] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def preBTSFunctionCall(o: BTSFunctionCall): MTransformer.PreResult[BTSFunctionCall] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def preBTSFormalExpPair(o: BTSFormalExpPair): MTransformer.PreResult[BTSFormalExpPair] = {
      return MTransformer.PreResult(T, MSome(o(pos = scrubPos(o.pos))))
    }

    override def preBlessAttr(o: BlessAttr): MTransformer.PreResult[BlessAttr] = {
      return MTransformer.PreResult(T, MSome(o(posOpt = scrubPos(o.posOpt))))
    }

    override def preAttr(o: Attr): MTransformer.PreResult[Attr] = {
      return MTransformer.PreResult(T, MSome(o(posOpt = scrubPos(o.posOpt))))
    }

    override def preResolvedAttr(o: ResolvedAttr): MTransformer.PreResult[ResolvedAttr] = {
      return MTransformer.PreResult(T, MSome(o(posOpt = scrubPos(o.posOpt))))
    }

    override def preTypedAttr(o: TypedAttr): MTransformer.PreResult[TypedAttr] = {
      return MTransformer.PreResult(T, MSome(o(posOpt = scrubPos(o.posOpt))))
    }
  }
}
